FROM python:slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir --trusted-host pypi.org --trusted-host files.pythonhosted.org --trusted-host pypi.python.org -r requirements.txt coverage

COPY utils/ ./utils/

ENTRYPOINT [ "python", "-m", "unittest" ]